import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import type { ProjectConfig } from '../types.js';
import { renderTemplate } from '../utils/template-renderer.js';

export async function generateApiClient(config: ProjectConfig, outputDir: string): Promise<void> {
  const data = {
    name: config.name,
    features: config.features,
    stack: config.stack,
    hasAuth: config.features.includes('auth'),
  };

  // TypeScript 클라이언트 (web, react-native)
  if (config.clients.includes('web') || config.clients.includes('react-native')) {
    const clientDir = path.join(outputDir, 'src', 'api');
    await mkdir(clientDir, { recursive: true });

    const tsClientContent = await renderTemplate('shared/api-client-ts.ejs', data);
    await writeFile(path.join(clientDir, 'client.ts'), tsClientContent);
  }

  // Kotlin 클라이언트 (android)
  if (config.clients.includes('android')) {
    const packageName = `com.example.${config.name.replace(/-/g, '')}`;
    const packagePath = packageName.replace(/\./g, '/');
    const kotlinDir = path.join(outputDir, 'android', 'app', 'src', 'main', 'kotlin', packagePath, 'api');
    await mkdir(kotlinDir, { recursive: true });

    const kotlinClientContent = await renderTemplate('shared/api-client-kotlin.ejs', data);
    await writeFile(path.join(kotlinDir, 'ApiClient.kt'), kotlinClientContent);
  }

  // Swift 클라이언트 (ios)
  if (config.clients.includes('ios')) {
    const appName = config.name.replace(/-/g, '');
    const swiftDir = path.join(outputDir, 'ios', appName, 'API');
    await mkdir(swiftDir, { recursive: true });

    const swiftClient = generateSwiftApiClient(config);
    await writeFile(path.join(swiftDir, 'APIClient.swift'), swiftClient);
  }

  // Dart 클라이언트 (flutter)
  if (config.clients.includes('flutter')) {
    const dartDir = path.join(outputDir, 'flutter', 'lib', 'api');
    await mkdir(dartDir, { recursive: true });

    const dartClient = generateDartApiClient(config);
    await writeFile(path.join(dartDir, 'api_client.dart'), dartClient);
  }
}

function generateSwiftApiClient(config: ProjectConfig): string {
  const hasAuth = config.features.includes('auth');
  return `import Foundation

// Type-safe API Client for ${config.name}
// Generated by Agentic Infra

enum APIError: Error {
    case invalidURL
    case httpError(statusCode: Int, message: String)
    case decodingError(Error)
    case networkError(Error)
}

struct APIResponse<T: Decodable>: Decodable {
    let data: T
}

actor APIClient {
    static let shared = APIClient()

    private let baseURL: String
    private let decoder = JSONDecoder()
    private let encoder = JSONEncoder()
${hasAuth ? '    private var authToken: String?\n' : ''}
    init(baseURL: String = ProcessInfo.processInfo.environment["API_BASE_URL"] ?? "http://localhost:3000/api") {
        self.baseURL = baseURL
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        encoder.keyEncodingStrategy = .convertToSnakeCase
    }
${hasAuth ? `
    func setAuthToken(_ token: String?) {
        authToken = token
    }
` : ''}
    func get<T: Decodable>(_ endpoint: String) async throws -> T {
        return try await request("GET", endpoint: endpoint)
    }

    func post<T: Decodable>(_ endpoint: String, body: some Encodable) async throws -> T {
        return try await request("POST", endpoint: endpoint, body: body)
    }

    func put<T: Decodable>(_ endpoint: String, body: some Encodable) async throws -> T {
        return try await request("PUT", endpoint: endpoint, body: body)
    }

    func delete<T: Decodable>(_ endpoint: String) async throws -> T {
        return try await request("DELETE", endpoint: endpoint)
    }

    private func request<T: Decodable>(
        _ method: String,
        endpoint: String,
        body: (some Encodable)? = nil as String?
    ) async throws -> T {
        guard let url = URL(string: "\\(baseURL)\\(endpoint)") else {
            throw APIError.invalidURL
        }

        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = 30
${hasAuth ? `
        if let token = authToken {
            request.setValue("Bearer \\(token)", forHTTPHeaderField: "Authorization")
        }
` : ''}
        if let body = body {
            request.httpBody = try encoder.encode(body)
        }

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw APIError.networkError(URLError(.badServerResponse))
        }

        guard (200...299).contains(httpResponse.statusCode) else {
            let message = String(data: data, encoding: .utf8) ?? "Unknown error"
            throw APIError.httpError(statusCode: httpResponse.statusCode, message: message)
        }

        do {
            return try decoder.decode(T.self, from: data)
        } catch {
            throw APIError.decodingError(error)
        }
    }
}
`;
}

function generateDartApiClient(config: ProjectConfig): string {
  const hasAuth = config.features.includes('auth');
  return `import 'dart:convert';
import 'package:http/http.dart' as http;

/// Type-safe API Client for ${config.name}
/// Generated by Agentic Infra

class ApiError implements Exception {
  final String message;
  final int statusCode;

  ApiError({required this.message, required this.statusCode});

  @override
  String toString() => 'ApiError($statusCode): $message';
}

class ApiClient {
  static final ApiClient _instance = ApiClient._internal();
  factory ApiClient() => _instance;
  ApiClient._internal();

  String _baseUrl = const String.fromEnvironment(
    'API_BASE_URL',
    defaultValue: 'http://localhost:3000/api',
  );
${hasAuth ? '  String? _authToken;\n' : ''}
  set baseUrl(String url) => _baseUrl = url;
${hasAuth ? `
  set authToken(String? token) => _authToken = token;
  String? get authToken => _authToken;
` : ''}
  Map<String, String> get _headers => {
        'Content-Type': 'application/json',
${hasAuth ? "        if (_authToken != null) 'Authorization': 'Bearer \\$_authToken',\n" : ''}      };

  Future<T> get<T>(String endpoint, T Function(dynamic) fromJson) async {
    return _request('GET', endpoint, fromJson);
  }

  Future<T> post<T>(
    String endpoint,
    Map<String, dynamic> body,
    T Function(dynamic) fromJson,
  ) async {
    return _request('POST', endpoint, fromJson, body: body);
  }

  Future<T> put<T>(
    String endpoint,
    Map<String, dynamic> body,
    T Function(dynamic) fromJson,
  ) async {
    return _request('PUT', endpoint, fromJson, body: body);
  }

  Future<T> delete<T>(String endpoint, T Function(dynamic) fromJson) async {
    return _request('DELETE', endpoint, fromJson);
  }

  Future<T> _request<T>(
    String method,
    String endpoint,
    T Function(dynamic) fromJson, {
    Map<String, dynamic>? body,
  }) async {
    final uri = Uri.parse('\\$_baseUrl\\$endpoint');

    late http.Response response;
    switch (method) {
      case 'GET':
        response = await http.get(uri, headers: _headers);
      case 'POST':
        response = await http.post(uri, headers: _headers, body: jsonEncode(body));
      case 'PUT':
        response = await http.put(uri, headers: _headers, body: jsonEncode(body));
      case 'DELETE':
        response = await http.delete(uri, headers: _headers);
      default:
        throw ArgumentError('Unsupported HTTP method: \\$method');
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw ApiError(
        message: response.body,
        statusCode: response.statusCode,
      );
    }

    final decoded = jsonDecode(response.body);
    return fromJson(decoded);
  }
}
`;
}
