import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import type { ProjectConfig } from '../types.js';
import { generateSupabase } from './supabase-generator.js';
import { generateAws } from './aws-generator.js';
import { generateVercel } from './vercel-generator.js';
import { generateClient } from './client-generator.js';

export async function generateProject(config: ProjectConfig, outputDir: string): Promise<void> {
  // 루트 디렉토리 생성
  await mkdir(outputDir, { recursive: true });

  // package.json 생성
  const packageJson = {
    name: config.name,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'echo "dev server not configured yet"',
      build: 'echo "build not configured yet"',
      test: 'echo "tests not configured yet"',
    },
    dependencies: {} as Record<string, string>,
    devDependencies: {
      typescript: '^5.7.2',
      '@types/node': '^22.10.5',
    },
  };

  await writeFile(
    path.join(outputDir, 'package.json'),
    JSON.stringify(packageJson, null, 2) + '\n',
  );

  // tsconfig.json 생성
  const tsconfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      outDir: './dist',
      rootDir: './src',
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  };

  await writeFile(
    path.join(outputDir, 'tsconfig.json'),
    JSON.stringify(tsconfig, null, 2) + '\n',
  );

  // README.md 생성
  const stackLabels: Record<string, string> = {
    supabase: 'Supabase',
    aws: 'AWS',
    hybrid: 'Supabase + AWS 하이브리드',
  };

  const readme = `# ${config.name}

> Generated by [Agentic Infra](https://github.com/agentic-infra)

## 스택

- **백엔드**: ${stackLabels[config.stack]}
- **클라이언트**: ${config.client === 'web' ? 'Next.js' : config.client === 'android' ? 'Android (Kotlin)' : 'Next.js + Android'}
- **기능**: ${config.features.join(', ')}

## 시작하기

\`\`\`bash
npm install
npm run dev
\`\`\`
`;

  await writeFile(path.join(outputDir, 'README.md'), readme);

  // src 디렉토리 생성
  await mkdir(path.join(outputDir, 'src'), { recursive: true });

  // 스택별 생성기 실행
  if (config.stack === 'supabase' || config.stack === 'hybrid') {
    await generateSupabase(config, outputDir);
  }
  if (config.stack === 'aws' || config.stack === 'hybrid') {
    await generateAws(config, outputDir);
  }
  if (config.deploy === 'vercel') {
    await generateVercel(config, outputDir);
  }

  // 클라이언트 생성기 실행
  await generateClient(config, outputDir);
}
